### ISSUE TITLE
Full factory reset command

### ISSUE THREAD

**Issue by saper-2** [igrr/atproto#10]
Hi,

I have replaced my router (and chaged my ISP ) few days ago, and I have new wifi SSID ofc... I have powered ESP module (with orginal fw) and I could not list WLAN networks (module just hungs-up on CWLAP)... 
So I thought would be very convenient to have command that could do a full factory reset: reset stored SSID(+passwd for them), CWMODE, CWSAP, etc. - all settings that can be changed by user to "factory default". 
Now we have ATF but it reset only few options for serial interface, it could do a full factory reset, or create new command?

**Comment by igrr** [comment]
Yeah, i suppose we can do a factory reset by wiping the flash region where the WiFi firmware stores its configs.
Will do this.

**Comment by igrr** [comment]
Okay, actually there was an error in commands manual, the correct syntax is `AT&F`.

Now there will be `AT&F0` for DCE settings, and `AT&F1` will additionally wipe WiFi config and reset baud rate to default.

**Comment by igrr** [comment]
Fixed in dc25577
