### ISSUE TITLE
No ready after boot

### ISSUE THREAD

**Issue by saper-2** [igrr/atproto#16]
Hi,

I just flashed your latest bin fw ( 8f6aadf 2014-11-18 ) into esp module but now there is no "ready" text after successful boot.
I tried at all baud rates that comes to my mind (9600,14400,19200,28800,38400,57600,115200,128k,256k) but just there is no "ready" text...

So, I got hit with idea: add to header/welcome/greeting text some more info in recognizable way that this is message (unsolicited result??) from boot  :

```
<cr>+boot:v:atproto:[BuildDate]:[commit_id]<cr>
ready<cr>
```

Explanation:
**+boot** - no need to explain :)
**v** - stands for Version info
Other fields explains itself :smile: 

**e.g.:**

```
<0>l`nnŽlnrŽ’’nŚŽlr’’nŚŽl<cr>
+boot:v:atproto:20141118:8f6aadf<cr>
ready<cr>
```

Personally I would love to get sth like that below, but this is my _crazy, personal wishful thinking_  :stuck_out_tongue_closed_eyes: and this goes off from official AT - before and after "ready" should be CR, but not in my case:

```
<cr>
+boot:v:atproto:20141118:8f6aadf<cr>
+boot:n:0032fd4b<cr>
+boot:ready<cr>
```

**n** - is for S/N and mac (are the same)

**Comment by igrr** [comment]
The response looks like this: `+IREADY:"atproto","0.1","a343e46"`.
This should be enough to determine _how_ to talk to the module. After that, you can use existing commands to get SN, MAC, etc.

**Comment by saper-2** [comment]
I know I'm bitching about this :smile: , but I will be insisting to add firmware compilation/release date to IREADY or +GMR. Why I'm so stubborn about this? 
Simple, commits number are random, so "what if" I will be checking if installed module is supported by my software. I check IREADY response or AT+GMR , I get commit number, but how software can recognize if this module is supported? It is impractical to keep all commits (or at least few latest that should be supported) numbers in sofware and check against them, but what if I install module with newer fw? Then in software there is no new commit-number so this module will be recognized as not supported. 
That's way I insist adding a date (in format YYYYMMDD (8 digits without separators)) so I can check if installed module fw is released after certain date. Date is rather very unique :smile:

**Comment by igrr** [comment]
Hey, no problem. I'll add compilation date to +GMR output.
But I would not make an assumption that all firmware versions will be backward-compatible. So newer version does not necessarily mean a compatible version.
I suppose I should increment version number when I make breaking changes to the API, so that firmware version can be used to establish compatibility.

**Comment by igrr** [comment]
Created #21.
