### ISSUE TITLE
How about a listen command for tcp/udp server support?

### ISSUE THREAD

**Issue by wizhippo** [igrr/atproto#2]

**Comment by wizhippo** [comment]
I saw your post on the esp8266 forum and see this is coming,

**Comment by igrr** [comment]
Reopened this so I don't forget.

**Comment by igrr** [comment]
Almost ready in 00eefbd, need to update commands manual.
ССing my post from esp8266.com with some updates:

---

Regarding the server: TCP mode is in a somewhat useable state, it might be worth trying. You use it as follows (sorry didn't have time to update commands manual on github):

```
AT+CIPLISTEN="TCP",12345,1024
+CIPLISTEN=6,12345,1024
```

This will create a TCP server listening on port 12345 with 1024 bytes rx buffer (separate buffer for each connection). Port and buffer size parameters are optional. The reply contains context id for the server (6), the port, and buffer size. You will need context id when you close the server. 

When the server gets an incomming connection, you get the following unsolicited result code:

```
+CIPACCEPT="0","192.169.0.120"
```

The first parameter is the context id of the client connection (you use it when you send and receive data to that client), the second one is the IP address of the client.
By the way, there's a limit of 5 client connections total, whether they are incoming (someone connects to your server) or outgoing (you connect to another server).
Now you work with this connection the same way, i.e. you send using `+CIPSENDI`, you get `+CIPDR` when the data is ready, and retrieve the data using `+CIPRD`. Supply context id given to you by `+CIPACCEPT`.
Don't forget to recycle the connection when it is no longer used (i.e. after `+CIPDISCONNECT` or `+CIPRECONNECT`) using `+CIPCLOSE`.

**Comment by wizhippo** [comment]
I have tried most recent with AT+CIPLISTEN="UDP",23,2048 and the module resets

**Comment by saper-2** [comment]
Last commit is from a month ago, so there are no new fixes. In esp8266 forum he said that he have trouble with accessing github...

**Comment by igrr** [comment]
I'm okay with github now, but unfortunately I don't have any bandwidth to
fix those issues at the moment. Sorry about that.
But the New Year holidays will likely give me a chance to work on this
project again.

**Comment by wizhippo** [comment]
Thank you.  To aid you when you have a moment enabling debug gives

https://gist.github.com/wizhippo/af1bf264c50ac1fc1627

**Comment by wizhippo** [comment]
Found the issue. Here is a patch to fix.  I may have missed something to clean up the udp server if destroyed.

https://gist.github.com/wizhippo/0b8cb04fce9adfec1c1d
