### ISSUE TITLE
Uploading the code

### ISSUE THREAD

**Issue by scargill** [igrr/atproto#4]
Hi
Bear in mind I'm a PC user - so compiling the code is giving me problems.. I thought I'd try out the binaries from your site -  using ESP8266flasher.exe I tried them one after the other. There is an address setting in the program but it does not seem to do anything. I've used it several times to upload the official code to the ESP-01 board no problem... but here I've tried uploading both of your bin files - and all I get when I connect a terminal to the board is a continuous string of garbage characters.  Any thoughts?

**Comment by igrr** [comment]
This ESP8266flasher.exe works only with complete firmware files that start at 0x00000. It doesn't seem to flash the second part at 0x40000 correctly. I'll add "full firmware" file generation early next week.

**Comment by scargill** [comment]
Oh well done I'll look forward to it.

**Comment by phil31** [comment]
hi scargill

I had the same trouble as you. igrr suggest me to use python Under Windows 

now, i successful flash the ESP8266, with 2.7 version of python.org :o)

regards

**Comment by scargill** [comment]
Would you like to do me (and others) a great favour and explain this making NO assumptions about Python knowledge. All I know about Python is that it sounds like a snake and is a computer language. C on the other hand I’ve pretty much mastered years ago.

**Comment by phil31** [comment]
well I was exactly in same case as you .. know nothing about python !
I simply install it from python.org (use the last 2.7 version instead of 3.xxx) then install the serial module : http://pyserial.sourceforge.net/ )

the igrr send me how to use the software :  https://github.com/themadinventor/esptool

#python esptool.py --port=/dev/tty.usbserial write_flash 0x00000 path/to/firmware/0x00000.bin
#python esptool.py --port=/dev/tty.usbserial write_flash 0x40000 path/to/firmware/0x40000.bin

If you're on Windows, you probably need to specify you COM port name instead of /dev/tty.usbserial, i.e. --port=COM3.
Ports above COM9 have to be specified with '\.\' prefix, i.e. \.\COM11. Some escaping of backslash characters may also be required, but I don't remember more from my Windows days. But you can find this in pyserial docs if necessary.

regards

nb : 
- you need to flash (flash mode using GPIO0 to low) each file one after one with a ON/OFF between each.
- the percentage stop at about 98% for booth file, but I work great !

**Comment by igrr** [comment]
Btw, Espressif has released a [GUI flash loader based on esptool](http://bbs.espressif.com/viewtopic.php?f=7&t=25).
They have posted a screenshot in [another topic](http://bbs.espressif.com/viewtopic.php?f=7&t=26):
[![Screenshot](https://guan.dk/esp8266/my-load-success.png)]
It also needs python, and some python libraries (pyserial and wxPython).

**Comment by phil31** [comment]
I had try to merge 2 bin files in one single
unfortunately, my result bin was not working as if I upload with python script :(

**Comment by scargill** [comment]
The funny thing is that did not work on my main machine, I installed Python – and now it does. I figured being an EXE file it did not need Python – so that’s solved – however, if I punch in the details of the .BIN files I have – nothing – the WIFI unit acts as a dead stone…

Pete.

**Comment by igrr** [comment]
> I figured being an EXE file it did not need Python

You aren't mixing up esptool and esptool.py, are you?

When you flash using esptool.py, you should get the following output (with paths and device names being an obvious difference):

```
$ python ../esptool/esptool.py --port=/dev/tty.usbserial-A7027BI1 write_flash 0x00000 /tmp/atproto-esp8266-3be7f3c/0x00000.bin 
Connecting
Erasing flash...
Writing at 0x00008800... (100 %) 
Leaving...
Traceback (most recent call last):
  File "../esptool/esptool.py", line 359, in <module>
    esp.flash_finish(False)
  File "../esptool/esptool.py", line 196, in flash_finish
    raise Exception('Failed to leave Flash mode')
Exception: Failed to leave Flash mode
$ python ../esptool/esptool.py --port=/dev/tty.usbserial-A7027BI1 write_flash 0x40000 /tmp/atproto-esp8266-3be7f3c/0x40000.bin 
Connecting
Erasing flash...
Writing at 0x00064000... (100 %) 
Leaving...
Traceback (most recent call last):
  File "../esptool/esptool.py", line 359, in <module>
    esp.flash_finish(False)
  File "../esptool/esptool.py", line 196, in flash_finish
    raise Exception('Failed to leave Flash mode')
Exception: Failed to leave Flash mode
```

Are you seeing something similar?

**Comment by scargill** [comment]
The one that says FRAME_TEST.EXE in a directory called FLASH_DOWNLOAD_TOOLS_V9.2.2.   I’ll come back to you later. Just off to see INTERSTELLAR!

**Comment by phil31** [comment]
Pete,

for me, "frame_test.exe" don't work .. but maybe I don't use correctly ?..

the esptool.py work, my output are similar to what igrr show, with the exception that that stop at about 97/98% before the "Exception: Failed to leave Flash mode"

but it's working when I reboot the module, the igrr firmware work on my module even if it is write 98% !

the AT set command work like a charm (do only some simple tests for now)

regards

**Comment by igrr** [comment]
I've added full firmware generation. You can download the latest binaries and flash `firmware.bin` file using your tool of choice, at zero offset.

**Comment by scargill** [comment]
Looks great but see last email – first command I tried to move from 9600 baud to 115200 as instructions – didn’t work.

Pete.

**Comment by scargill** [comment]
Just tried blowing the code – worked first time – and responds to AT commands at 9600 – however looking at the docs – the command AT+IPR=115200 should work – but it does not.

Pete.

**Comment by igrr** [comment]
How exactly does it not work? What output are you seeing? I think i need
more info to troubleshoot your issue.

Here's what I get:

AT+IPR=?

+IPR:(0),(9600,19200,38400,57600,74880,115200,230400,460800,921600)

AT+IPR?

+IPR:9600

AT+IPR=115200

OK

And after that, restarting the terminal at 115200:

AT+IPR?

+IPR:115200

**Comment by scargill** [comment]
I’ve tried blowing the software twice now – same result both times – endless loop.

**Comment by scargill** [comment]
I can offer any feedback you like but as I’m in the UK we are soon giving up for the night J I’d be very pleased to see this running  especially as you have basic TCP/IP listen and send which is exactly what I need…

Pete.

**Comment by scargill** [comment]
And yes once basically working I would love to set up the development environment.

Pete.

**Comment by igrr** [comment]
Will try again tomorrow, maybe I have messed up the bin's somehow.

**Comment by igrr** [comment]
Pete, first of all,

> putting the two files at 0x0000 and 0x4000 respectively

You have to flash at 0x00000 and 0x40000, that's one extra zero.

And one more thing, in your output:

> Frankenstein ESP8266 Firmware 
> Powered by Antares 0.2-rc1, Insane Mushroom 
> (c) Andrew 'Necromant' Andrianov 2014 andrew@ncrmnt.org 

That's a different firmware, https://github.com/nekromant/esp8266-frankenstein. You either need to report issues against that project, or use binaries downloaded from my site :)

By the way, in the binary archives I distribute there is a firmware.bin file. You can just flash this file at zero offset, no second file required. Maybe this will help.

**Comment by scargill** [comment]
Hi 

Sorry - I wrote that way too late last night :-) Clearly I meant 0x40000... and apologies for the confusion I am trying 2 sets of firmware out right now. 

Right - THIS MORNING I've grabbed your single file firmware.bin from your website. After blowing the firmware with ESP8266_FLASHER.EXE, the AT command works at 9600 baud as previously reported and returns OK.

Also AT+IPR? reports back 9600 baud.But setting - and I've even copied and pasted from your info above..

AT+IPR=115200
c_ÇÏRÂöfJúfJSúâî8;

That LOOKS like it is responding at a different baud rate but if I then switch to 115Kb I get nothing, switch to 9600 and it's still working - in other words it is not changing baud rate...

**Comment by igrr** [comment]
Okay, this happens when your terminal application sends CR LF at the end of the command. It only happens with AT+IPR command because the trailing LF is not handled correctly after the baud rate is changed.

I understand that there are some terminals that can not be configured to issue just CR (as specified in V.250) so i will definitely fix this. Created a new issue for this, please post any follow-ups there: https://github.com/igrr/atproto/issues/9

In the meantime, see if you can configure your terminal to end lines with CR.

**Comment by scargill** [comment]
Well, that made a difference! Ok, testing… got a connection to the router.

**Comment by scargill** [comment]
Next question as these commands are slightly different to before..

I have the board talking to my Access point – and I’ve told it I want a TCP connection on port 4000 (AT+CIPCREATE="TCP",4000).

Not sure where to go from here.. I want it listening on port 4000 and sending results of incoming data before replying to it (I have a mobile phone app which will send simple text commands (NETIO) and I’ll then send simple responses.   All of this works on the original code (other than the BUSY S problem of course.

Not sure what I should be doing to take in incoming data??

Pete.

**Comment by igrr** [comment]
I'll add a few examples to explain common usage scenarios.
Just to clarify: you need esp8266 to act as a TCP server?

**Comment by phil31** [comment]
for me, yes i need ESP8266 to act as TCP server

**Comment by scargill** [comment]
Hi

Well of course that would be nice – but no right now it needs to act as a simple TCP/IP listener.  I send messages to it from a mobile phone using NETIO – like LAMP1ON etc and it then sends back messages to say OK or the status of the lamp etc. I can do this with the standard software but it locks up with that BUSY message…

So typically right now I start as follows… the “SerialFinder” is just a routine that takes in the serial input and looks for keywords with a potential timeout..

char PROGMEM cmd[]="AT+CIPSERVER=1,4000";
  Serial.print(F("\r\nSending ")); 
  Serial.println(cmd);
  Serial1.println(cmd);
  SerialFinder(Serial1,Serial,"OK",3000,0,NULL,0);

If you want further detail let me know…
Pete.

**Comment by scargill** [comment]
The other thing I need is for it to act as a client. I have a web page in PHP which returns some text when called and I need to grab that (time, date, lighting up time, dawn time etc). Again that works with the standard code (most of the time)
